In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_excel('41477_2022_1339_MOESM2_ESM.xlsx', sheet_name='Present-day olive-growing areas')

In [5]:
df

,Dataset - Present-day olive-growing areas,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Temperatures (Â°C),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Longitude,Latitude,January,February,March,April,May,June,July,August,...,March,April,May,June,July,August,September,October,November,December
3,-9.25,39.25,11.6,12.3,13.6,16.9,19.5,20.2,22.6,22.7,...,72.12,69.08,44.75,26.5,9.12,9.12,39.54,96.25,103.62,121.67
4,-8.75,37.25,12.3,12.7,13.8,17.4,20.1,20.5,23.2,23.5,...,50.83,44.75,23.46,8.25,3.04,3.04,18.25,71.92,85.38,100.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,37.25,36.25,6.8,8.6,11.9,18.7,24,26.6,29.4,29.3,...,41.71,26.5,8.25,0,0,0,0,32.38,27.58,63.88
324,37.25,36.75,6.1,7.6,11.1,18,23.2,25.9,29.2,29.1,...,63,41.71,17.38,0,0,3.04,3.04,41.5,39.75,88.21
325,37.75,36.75,6.1,7.7,11.5,18.4,23.6,26.8,30.3,29.9,...,50.83,32.58,11.29,0,0,3.04,3.04,32.38,30.62,76.04
326,38.25,36.75,6.4,8,11.9,18.9,24.3,27.5,31.1,30.5,...,47.79,29.54,11.29,0,0,0,0,29.33,24.54,69.96
327,38.75,36.75,6.7,8.3,12.3,19.2,24.7,27.9,31.4,30.9,...,47.79,32.58,14.33,0,0,0,0,29.33,21.5,69.96